### ISSUE TITLE
feat: retry in queue notification

### ISSUE THREAD

**Issue by jonas-elias** [jonas-elias/banking#54]
**Is the feature request related to a problem? Please describe:**
The request notification break with 500> status code, but queue not retry.

**Describe the expected solution:**
Add retry in queue notification `/var/www/app/Job/NotificationEmailJob.php`

`composer require hyperf/retry`

**Comment by berkantkockaya** [comment]
To address the issue:

	- Install the hyperf/retry package by running composer require hyperf/retry.
	- Modify the /var/www/app/Job/NotificationEmailJob.php file to include a retry mechanism for the queue notification. Ensure that the notification will retry on failure (status code 500 or higher).

This should help implement a retry feature in the queue notification system.

**Comment by jonas-elias** [comment]
> To address the issue:
> 
> ```
> - Install the hyperf/retry package by running composer require hyperf/retry.
> - Modify the /var/www/app/Job/NotificationEmailJob.php file to include a retry mechanism for the queue notification. Ensure that the notification will retry on failure (status code 500 or higher).
> ```
> 
> This should help implement a retry feature in the queue notification system.

positive 👍🏻
